# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indexUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Index(object):
    def setupUi(self, Index):
        Index.setObjectName(_fromUtf8("Index"))
        Index.resize(1532, 963)
        self.centralwidget = QtGui.QWidget(Index)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.canvas = QtGui.QWidget(self.centralwidget)
        self.canvas.setEnabled(True)
        self.canvas.setMinimumSize(QtCore.QSize(1200, 900))
        self.canvas.setObjectName(_fromUtf8("canvas"))
        self.gridLayoutWidget = QtGui.QWidget(self.canvas)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1201, 901))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.mplvl = QtGui.QGridLayout(self.gridLayoutWidget)
        self.mplvl.setMargin(0)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_7.addWidget(self.canvas, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout.addWidget(self.groupBox_3, 17, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout.addWidget(self.groupBox_9, 3, 1, 1, 1)
        self.distance_button = QtGui.QPushButton(self.centralwidget)
        self.distance_button.setObjectName(_fromUtf8("distance_button"))
        self.gridLayout.addWidget(self.distance_button, 10, 1, 1, 3)
        self.ListBox_d_2 = QtGui.QListWidget(self.centralwidget)
        self.ListBox_d_2.setObjectName(_fromUtf8("ListBox_d_2"))
        self.gridLayout.addWidget(self.ListBox_d_2, 4, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.space_group_label = QtGui.QLabel(self.groupBox)
        self.space_group_label.setObjectName(_fromUtf8("space_group_label"))
        self.gridLayout_2.addWidget(self.space_group_label, 17, 1, 1, 1)
        self.d_label_var = QtGui.QLabel(self.groupBox)
        self.d_label_var.setText(_fromUtf8(""))
        self.d_label_var.setObjectName(_fromUtf8("d_label_var"))
        self.gridLayout_2.addWidget(self.d_label_var, 11, 5, 1, 1)
        self.b_label = QtGui.QLabel(self.groupBox)
        self.b_label.setObjectName(_fromUtf8("b_label"))
        self.gridLayout_2.addWidget(self.b_label, 5, 0, 1, 1)
        self.gamma_entry = QtGui.QLineEdit(self.groupBox)
        self.gamma_entry.setObjectName(_fromUtf8("gamma_entry"))
        self.gridLayout_2.addWidget(self.gamma_entry, 9, 4, 1, 1)
        self.indice_label = QtGui.QLabel(self.groupBox)
        self.indice_label.setObjectName(_fromUtf8("indice_label"))
        self.gridLayout_2.addWidget(self.indice_label, 11, 1, 1, 1)
        self.n_label = QtGui.QLabel(self.groupBox)
        self.n_label.setObjectName(_fromUtf8("n_label"))
        self.gridLayout_2.addWidget(self.n_label, 15, 1, 1, 1)
        self.n_entry = QtGui.QLineEdit(self.groupBox)
        self.n_entry.setObjectName(_fromUtf8("n_entry"))
        self.gridLayout_2.addWidget(self.n_entry, 15, 4, 1, 1)
        self.beta_label = QtGui.QLabel(self.groupBox)
        self.beta_label.setObjectName(_fromUtf8("beta_label"))
        self.gridLayout_2.addWidget(self.beta_label, 5, 2, 1, 1)
        self.b_entry = QtGui.QLineEdit(self.groupBox)
        self.b_entry.setObjectName(_fromUtf8("b_entry"))
        self.gridLayout_2.addWidget(self.b_entry, 5, 1, 1, 1)
        self.c_entry = QtGui.QLineEdit(self.groupBox)
        self.c_entry.setObjectName(_fromUtf8("c_entry"))
        self.gridLayout_2.addWidget(self.c_entry, 9, 1, 1, 1)
        self.c_label = QtGui.QLabel(self.groupBox)
        self.c_label.setObjectName(_fromUtf8("c_label"))
        self.gridLayout_2.addWidget(self.c_label, 9, 0, 1, 1)
        self.Button_reset = QtGui.QPushButton(self.groupBox)
        self.Button_reset.setObjectName(_fromUtf8("Button_reset"))
        self.gridLayout_2.addWidget(self.Button_reset, 24, 1, 1, 4)
        self.SpaceGroup_box = QtGui.QComboBox(self.groupBox)
        self.SpaceGroup_box.setObjectName(_fromUtf8("SpaceGroup_box"))
        self.gridLayout_2.addWidget(self.SpaceGroup_box, 17, 2, 1, 3)
        self.indice_entry = QtGui.QLineEdit(self.groupBox)
        self.indice_entry.setObjectName(_fromUtf8("indice_entry"))
        self.gridLayout_2.addWidget(self.indice_entry, 11, 4, 1, 1)
        self.Calib_box = QtGui.QComboBox(self.groupBox)
        self.Calib_box.setObjectName(_fromUtf8("Calib_box"))
        self.gridLayout_2.addWidget(self.Calib_box, 18, 2, 1, 3)
        self.beta_entry = QtGui.QLineEdit(self.groupBox)
        self.beta_entry.setObjectName(_fromUtf8("beta_entry"))
        self.gridLayout_2.addWidget(self.beta_entry, 5, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 16, 1, 1, 1)
        self.Calib_label = QtGui.QLabel(self.groupBox)
        self.Calib_label.setObjectName(_fromUtf8("Calib_label"))
        self.gridLayout_2.addWidget(self.Calib_label, 18, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 19, 2, 1, 1)
        self.gamma_label = QtGui.QLabel(self.groupBox)
        self.gamma_label.setObjectName(_fromUtf8("gamma_label"))
        self.gridLayout_2.addWidget(self.gamma_label, 9, 2, 1, 1)
        self.Button_reset_all = QtGui.QPushButton(self.groupBox)
        self.Button_reset_all.setObjectName(_fromUtf8("Button_reset_all"))
        self.gridLayout_2.addWidget(self.Button_reset_all, 25, 1, 1, 4)
        self.a_entry = QtGui.QLineEdit(self.groupBox)
        self.a_entry.setObjectName(_fromUtf8("a_entry"))
        self.gridLayout_2.addWidget(self.a_entry, 1, 1, 1, 1)
        self.a_label = QtGui.QLabel(self.groupBox)
        self.a_label.setObjectName(_fromUtf8("a_label"))
        self.gridLayout_2.addWidget(self.a_label, 1, 0, 1, 1)
        self.alpha_entry = QtGui.QLineEdit(self.groupBox)
        self.alpha_entry.setObjectName(_fromUtf8("alpha_entry"))
        self.gridLayout_2.addWidget(self.alpha_entry, 1, 4, 1, 1)
        self.alpha_label = QtGui.QLabel(self.groupBox)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout_2.addWidget(self.alpha_label, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 3)
        self.orientation_button = QtGui.QPushButton(self.centralwidget)
        self.orientation_button.setObjectName(_fromUtf8("orientation_button"))
        self.gridLayout.addWidget(self.orientation_button, 15, 1, 1, 3)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout.addWidget(self.groupBox_5, 3, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout.addWidget(self.groupBox_2, 12, 1, 1, 3)
        self.ListBox_theo = QtGui.QListWidget(self.centralwidget)
        self.ListBox_theo.setObjectName(_fromUtf8("ListBox_theo"))
        self.gridLayout.addWidget(self.ListBox_theo, 4, 3, 1, 1)
        self.diff_spot_Listbox = QtGui.QListWidget(self.centralwidget)
        self.diff_spot_Listbox.setObjectName(_fromUtf8("diff_spot_Listbox"))
        self.gridLayout.addWidget(self.diff_spot_Listbox, 13, 1, 1, 3)
        self.add_spot_button = QtGui.QPushButton(self.centralwidget)
        self.add_spot_button.setObjectName(_fromUtf8("add_spot_button"))
        self.gridLayout.addWidget(self.add_spot_button, 14, 1, 1, 2)
        self.remove_spot_button = QtGui.QPushButton(self.centralwidget)
        self.remove_spot_button.setObjectName(_fromUtf8("remove_spot_button"))
        self.gridLayout.addWidget(self.remove_spot_button, 14, 3, 1, 1)
        self.euler_listbox = QtGui.QListWidget(self.centralwidget)
        self.euler_listbox.setObjectName(_fromUtf8("euler_listbox"))
        self.gridLayout.addWidget(self.euler_listbox, 18, 1, 1, 3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout.addWidget(self.groupBox_4, 11, 1, 1, 1)
        self.tilt_entry = QtGui.QLineEdit(self.centralwidget)
        self.tilt_entry.setObjectName(_fromUtf8("tilt_entry"))
        self.gridLayout.addWidget(self.tilt_entry, 11, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 1, 1, 1)
        Index.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Index)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1532, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuStructure = QtGui.QMenu(self.menubar)
        self.menuStructure.setObjectName(_fromUtf8("menuStructure"))
        self.menuSpectrum = QtGui.QMenu(self.menubar)
        self.menuSpectrum.setObjectName(_fromUtf8("menuSpectrum"))
        Index.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Index)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Index.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(Index)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(Index)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_spectrum = QtGui.QAction(Index)
        self.actionCalculate_spectrum.setObjectName(_fromUtf8("actionCalculate_spectrum"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menuSpectrum.addAction(self.actionCalculate_spectrum)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuStructure.menuAction())
        self.menubar.addAction(self.menuSpectrum.menuAction())

        self.retranslateUi(Index)
        QtCore.QMetaObject.connectSlotsByName(Index)
        Index.setTabOrder(self.a_entry, self.b_entry)
        Index.setTabOrder(self.b_entry, self.c_entry)
        Index.setTabOrder(self.c_entry, self.alpha_entry)
        Index.setTabOrder(self.alpha_entry, self.beta_entry)
        Index.setTabOrder(self.beta_entry, self.gamma_entry)
        Index.setTabOrder(self.gamma_entry, self.indice_entry)
        Index.setTabOrder(self.indice_entry, self.n_entry)
        Index.setTabOrder(self.n_entry, self.SpaceGroup_box)
        Index.setTabOrder(self.SpaceGroup_box, self.Calib_box)
        Index.setTabOrder(self.Calib_box, self.Button_reset)
        Index.setTabOrder(self.Button_reset, self.Button_reset_all)
        Index.setTabOrder(self.Button_reset_all, self.distance_button)
        Index.setTabOrder(self.distance_button, self.orientation_button)

    def retranslateUi(self, Index):
        Index.setWindowTitle(_translate("Index", "Index", None))
        self.groupBox_3.setTitle(_translate("Index", "Euler angles", None))
        self.groupBox_9.setTitle(_translate("Index", "Distance, inclination", None))
        self.distance_button.setText(_translate("Index", "Find diffraction spots", None))
        self.groupBox.setTitle(_translate("Index", "Crystal Parameters", None))
        self.space_group_label.setText(_translate("Index", "Space group", None))
        self.b_label.setText(_translate("Index", "b", None))
        self.indice_label.setText(_translate("Index", "Max Indices", None))
        self.n_label.setText(_translate("Index", "Number of spots", None))
        self.beta_label.setText(_translate("Index", "<p>&beta;</p>", None))
        self.c_label.setText(_translate("Index", "c", None))
        self.Button_reset.setText(_translate("Index", "Reset points", None))
        self.Calib_label.setText(_translate("Index", "Calibrations", None))
        self.gamma_label.setText(_translate("Index", "<p>&gamma;</p>", None))
        self.Button_reset_all.setText(_translate("Index", "Reset all", None))
        self.a_label.setText(_translate("Index", "a", None))
        self.alpha_label.setText(_translate("Index", "<p>&alpha;</p>", None))
        self.orientation_button.setText(_translate("Index", "Get orientation", None))
        self.groupBox_5.setTitle(_translate("Index", "Theo. distance", None))
        self.groupBox_2.setTitle(_translate("Index", "Diffraction spots", None))
        self.add_spot_button.setText(_translate("Index", "Add spot", None))
        self.remove_spot_button.setText(_translate("Index", "Remove", None))
        self.groupBox_4.setTitle(_translate("Index", "Tilt angle", None))
        self.menuSave.setTitle(_translate("Index", "Open", None))
        self.menuStructure.setTitle(_translate("Index", "Structure", None))
        self.menuSpectrum.setTitle(_translate("Index", "Spectrum", None))
        self.actionSave_figure.setText(_translate("Index", "Open image", None))
        self.actionCalculate_Schmid_factor.setText(_translate("Index", "calculate Schmid factor", None))
        self.actionCalculate_spectrum.setText(_translate("Index", "Plot spectrum", None))

