# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indexUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Index(object):
    def setupUi(self, Index):
        Index.setObjectName(_fromUtf8("Index"))
        Index.resize(1200, 773)
        self.centralwidget = QtGui.QWidget(Index)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mplvl = QtGui.QGridLayout()
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_2.addLayout(self.mplvl, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.abc_label = QtGui.QLabel(self.groupBox)
        self.abc_label.setObjectName(_fromUtf8("abc_label"))
        self.gridLayout.addWidget(self.abc_label, 0, 0, 1, 1)
        self.abc_entry = QtGui.QLineEdit(self.groupBox)
        self.abc_entry.setObjectName(_fromUtf8("abc_entry"))
        self.gridLayout.addWidget(self.abc_entry, 0, 1, 1, 1)
        self.alpha_label = QtGui.QLabel(self.groupBox)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout.addWidget(self.alpha_label, 1, 0, 1, 1)
        self.alphabetagamma_entry = QtGui.QLineEdit(self.groupBox)
        self.alphabetagamma_entry.setObjectName(_fromUtf8("alphabetagamma_entry"))
        self.gridLayout.addWidget(self.alphabetagamma_entry, 1, 1, 1, 1)
        self.indice_label = QtGui.QLabel(self.groupBox)
        self.indice_label.setObjectName(_fromUtf8("indice_label"))
        self.gridLayout.addWidget(self.indice_label, 2, 0, 1, 1)
        self.indice_entry = QtGui.QLineEdit(self.groupBox)
        self.indice_entry.setObjectName(_fromUtf8("indice_entry"))
        self.gridLayout.addWidget(self.indice_entry, 2, 1, 1, 1)
        self.n_label = QtGui.QLabel(self.groupBox)
        self.n_label.setObjectName(_fromUtf8("n_label"))
        self.gridLayout.addWidget(self.n_label, 3, 0, 1, 1)
        self.n_entry = QtGui.QLineEdit(self.groupBox)
        self.n_entry.setObjectName(_fromUtf8("n_entry"))
        self.gridLayout.addWidget(self.n_entry, 3, 1, 1, 1)
        self.space_group_label = QtGui.QLabel(self.groupBox)
        self.space_group_label.setObjectName(_fromUtf8("space_group_label"))
        self.gridLayout.addWidget(self.space_group_label, 4, 0, 1, 1)
        self.SpaceGroup_box = QtGui.QComboBox(self.groupBox)
        self.SpaceGroup_box.setObjectName(_fromUtf8("SpaceGroup_box"))
        self.gridLayout.addWidget(self.SpaceGroup_box, 4, 1, 1, 1)
        self.Calib_label = QtGui.QLabel(self.groupBox)
        self.Calib_label.setObjectName(_fromUtf8("Calib_label"))
        self.gridLayout.addWidget(self.Calib_label, 5, 0, 1, 1)
        self.Calib_box = QtGui.QComboBox(self.groupBox)
        self.Calib_box.setObjectName(_fromUtf8("Calib_box"))
        self.gridLayout.addWidget(self.Calib_box, 5, 1, 1, 1)
        self.tilt_axis_angle_label = QtGui.QLabel(self.groupBox)
        self.tilt_axis_angle_label.setObjectName(_fromUtf8("tilt_axis_angle_label"))
        self.gridLayout.addWidget(self.tilt_axis_angle_label, 6, 0, 1, 1)
        self.tilt_axis_angle_entry = QtGui.QLineEdit(self.groupBox)
        self.tilt_axis_angle_entry.setObjectName(_fromUtf8("tilt_axis_angle_entry"))
        self.gridLayout.addWidget(self.tilt_axis_angle_entry, 6, 1, 1, 1)
        self.Button_reset = QtGui.QPushButton(self.groupBox)
        self.Button_reset.setObjectName(_fromUtf8("Button_reset"))
        self.gridLayout.addWidget(self.Button_reset, 7, 0, 1, 1)
        self.Button_reset_all = QtGui.QPushButton(self.groupBox)
        self.Button_reset_all.setObjectName(_fromUtf8("Button_reset_all"))
        self.gridLayout.addWidget(self.Button_reset_all, 7, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 1, 1, 1)
        self.ListBox_d_2 = QtGui.QListWidget(self.groupBox)
        self.ListBox_d_2.setObjectName(_fromUtf8("ListBox_d_2"))
        self.gridLayout.addWidget(self.ListBox_d_2, 9, 0, 1, 1)
        self.ListBox_theo = QtGui.QListWidget(self.groupBox)
        self.ListBox_theo.setObjectName(_fromUtf8("ListBox_theo"))
        self.gridLayout.addWidget(self.ListBox_theo, 9, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.tilt_entry = QtGui.QLineEdit(self.groupBox)
        self.tilt_entry.setObjectName(_fromUtf8("tilt_entry"))
        self.gridLayout.addWidget(self.tilt_entry, 11, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 12, 0, 1, 1)
        self.diff_spot_Listbox = QtGui.QListWidget(self.groupBox)
        self.diff_spot_Listbox.setObjectName(_fromUtf8("diff_spot_Listbox"))
        self.gridLayout.addWidget(self.diff_spot_Listbox, 12, 1, 1, 1)
        self.add_spot_button = QtGui.QPushButton(self.groupBox)
        self.add_spot_button.setObjectName(_fromUtf8("add_spot_button"))
        self.gridLayout.addWidget(self.add_spot_button, 13, 0, 1, 1)
        self.remove_spot_button = QtGui.QPushButton(self.groupBox)
        self.remove_spot_button.setObjectName(_fromUtf8("remove_spot_button"))
        self.gridLayout.addWidget(self.remove_spot_button, 13, 1, 1, 1)
        self.euler_listbox = QtGui.QListWidget(self.groupBox)
        self.euler_listbox.setObjectName(_fromUtf8("euler_listbox"))
        self.gridLayout.addWidget(self.euler_listbox, 15, 0, 1, 2)
        self.distance_button = QtGui.QPushButton(self.groupBox)
        self.distance_button.setObjectName(_fromUtf8("distance_button"))
        self.gridLayout.addWidget(self.distance_button, 10, 0, 1, 1)
        self.orientation_button = QtGui.QPushButton(self.groupBox)
        self.orientation_button.setObjectName(_fromUtf8("orientation_button"))
        self.gridLayout.addWidget(self.orientation_button, 14, 0, 1, 1)
        self.abc_label.raise_()
        self.abc_label.raise_()
        self.alpha_label.raise_()
        self.indice_label.raise_()
        self.n_label.raise_()
        self.space_group_label.raise_()
        self.Calib_label.raise_()
        self.Calib_box.raise_()
        self.SpaceGroup_box.raise_()
        self.n_entry.raise_()
        self.indice_entry.raise_()
        self.alphabetagamma_entry.raise_()
        self.abc_entry.raise_()
        self.tilt_axis_angle_label.raise_()
        self.tilt_axis_angle_entry.raise_()
        self.Button_reset.raise_()
        self.Button_reset_all.raise_()
        self.label.raise_()
        self.distance_button.raise_()
        self.label_3.raise_()
        self.tilt_entry.raise_()
        self.label_4.raise_()
        self.diff_spot_Listbox.raise_()
        self.add_spot_button.raise_()
        self.remove_spot_button.raise_()
        self.orientation_button.raise_()
        self.ListBox_d_2.raise_()
        self.label_2.raise_()
        self.ListBox_theo.raise_()
        self.euler_listbox.raise_()
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        Index.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Index)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuStructure = QtGui.QMenu(self.menubar)
        self.menuStructure.setObjectName(_fromUtf8("menuStructure"))
        self.menuSpectrum = QtGui.QMenu(self.menubar)
        self.menuSpectrum.setObjectName(_fromUtf8("menuSpectrum"))
        Index.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Index)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Index.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(Index)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(Index)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_spectrum = QtGui.QAction(Index)
        self.actionCalculate_spectrum.setObjectName(_fromUtf8("actionCalculate_spectrum"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menuSpectrum.addAction(self.actionCalculate_spectrum)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuStructure.menuAction())
        self.menubar.addAction(self.menuSpectrum.menuAction())

        self.retranslateUi(Index)
        QtCore.QMetaObject.connectSlotsByName(Index)
        Index.setTabOrder(self.abc_entry, self.alphabetagamma_entry)
        Index.setTabOrder(self.alphabetagamma_entry, self.indice_entry)
        Index.setTabOrder(self.indice_entry, self.n_entry)
        Index.setTabOrder(self.n_entry, self.SpaceGroup_box)
        Index.setTabOrder(self.SpaceGroup_box, self.Calib_box)
        Index.setTabOrder(self.Calib_box, self.tilt_axis_angle_entry)
        Index.setTabOrder(self.tilt_axis_angle_entry, self.Button_reset)
        Index.setTabOrder(self.Button_reset, self.Button_reset_all)
        Index.setTabOrder(self.Button_reset_all, self.ListBox_d_2)
        Index.setTabOrder(self.ListBox_d_2, self.ListBox_theo)
        Index.setTabOrder(self.ListBox_theo, self.distance_button)
        Index.setTabOrder(self.distance_button, self.tilt_entry)
        Index.setTabOrder(self.tilt_entry, self.diff_spot_Listbox)
        Index.setTabOrder(self.diff_spot_Listbox, self.add_spot_button)
        Index.setTabOrder(self.add_spot_button, self.remove_spot_button)
        Index.setTabOrder(self.remove_spot_button, self.orientation_button)

    def retranslateUi(self, Index):
        Index.setWindowTitle(_translate("Index", "Index", None))
        self.abc_label.setText(_translate("Index", "a,b,c", None))
        self.alpha_label.setText(_translate("Index", "<html><head/><body><p>α,β,γ</p></body></html>", None))
        self.indice_label.setText(_translate("Index", "Max Indices", None))
        self.n_label.setText(_translate("Index", "Number of spots", None))
        self.space_group_label.setText(_translate("Index", "Space group", None))
        self.Calib_label.setText(_translate("Index", "Calibrations", None))
        self.tilt_axis_angle_label.setText(_translate("Index", "tilt-axis/y angle", None))
        self.Button_reset.setText(_translate("Index", "Reset points", None))
        self.Button_reset_all.setText(_translate("Index", "Reset all", None))
        self.label.setText(_translate("Index", "<html><head/><body><p><span style=\" font-weight:600;\">Dist., inclination</span></p></body></html>", None))
        self.label_2.setText(_translate("Index", "<html><head/><body><p><span style=\" font-weight:600;\">Dist. Theo</span></p></body></html>", None))
        self.label_3.setText(_translate("Index", "<html><head/><body><p><span style=\" font-weight:600;\">Tilt angles</span></p></body></html>", None))
        self.label_4.setText(_translate("Index", "<html><head/><body><p><span style=\" font-weight:600;\">Diffraction spots</span></p></body></html>", None))
        self.add_spot_button.setText(_translate("Index", "Add spot", None))
        self.remove_spot_button.setText(_translate("Index", "Remove", None))
        self.distance_button.setText(_translate("Index", "Find diffraction spots", None))
        self.orientation_button.setText(_translate("Index", "Get orientation", None))
        self.menuSave.setTitle(_translate("Index", "Open", None))
        self.menuStructure.setTitle(_translate("Index", "Structure", None))
        self.menuSpectrum.setTitle(_translate("Index", "Spectrum", None))
        self.actionSave_figure.setText(_translate("Index", "Open image", None))
        self.actionCalculate_Schmid_factor.setText(_translate("Index", "calculate Schmid factor", None))
        self.actionCalculate_spectrum.setText(_translate("Index", "Plot spectrum", None))

